apiVersion: apps/v1
kind: Deployment

metadata:
  name: spring-deployment

# Deployment 세부 정보
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-app #  backend-app 레이블을 가진 파드들을 배포한다

  # 배포할 파드 내용 정의
  template:
    metadata:
      labels: # 배포할 파드 카테고리
        app: backend-app
    spec:
      containers:
        - name: spring-container
          image: spring-server
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: MY_ACCOUNT
              valueFrom:
                configMapKeyRef:
                  name: spring-config
                  key: my-account
            - name: MY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spring-secret
                  key: my-password


# kubectl apply -f spring-deployment.yaml

# kubectl get deployment
# -> NAME               READY   UP-TO-DATE   AVAILABLE   AGE
# -> spring-deployment   3/3     3            3           65s

# kubectl get replicaset
# -> NAME                          DESIRED   CURRENT   READY   AGE
# -> spring-deployment-7565bdff49   3         3         3       2m3s

# kubectl get pods
# spring-deployment-7565bdff49-2hdgz   1/1     Running   0          5s
# spring-deployment-7565bdff49-lhk2w   1/1     Running   0          5s
# spring-deployment-7565bdff49-qgx2f   1/1     Running   0          5s

#  kubectl get configmap
# -> NAME           DATA   AGE
# -> spring-config   2      3m

# kubectl rollout restart deployment spring-deployment # deployment 재시작
# deployment.apps/spring-deployment restarted

# 리소스 사용량
# kubectl top pod
# NAME                                CPU(cores)   MEMORY(bytes)
# nest-deployment-547f5764c8-52zvg    1m           27Mi
# nest-deployment-547f5764c8-6pts7    1m           27Mi
# nest-deployment-547f5764c8-gzf4s    1m           26Mi
# nest-deployment-547f5764c8-kvxkm    1m           26Mi
# spring-deployment-697f4c7c4-56zch   1m           155Mi
# spring-deployment-697f4c7c4-tspbc   1m           151Mi
# spring-deployment-697f4c7c4-x2fp8   1m           151Mi

# kubectl top node
# NAME                   CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
# lima-rancher-desktop   37m          1%     2918Mi          49%