apiVersion: v1
kind: Pod

metadata:
  name: nginx-pod

spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80 # 8080이라고 작성해도 컨테이너 내부에서 실제 8080으로 띄어지지 않음, 그냥 가독성용

# kubectl apply -f nginx-pod.yaml
# -> pod/nginx-pod created

# kubectl get pods
# -> NAME        READY   STATUS    RESTARTS   AGE
# -> nginx-pod   1/1     Running   0          70s