apiVersion: v1
kind: Pod

metadata:
  name: nginx-pod

spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80 # 8080이라고 작성해도 컨테이너 내부에서 실제 8080으로 띄어지지 않음, 그냥 가독성용

## pod 생성
# kubectl apply -f nginx-pod.yaml
# -> pod/nginx-pod created

# kubectl get pods
# -> NAME        READY   STATUS    RESTARTS   AGE
# -> nginx-pod   1/1     Running   0          70s

## pod 확인

# 1. pod 접속하는 방법
# kubectl exec -it nginx-pod -- bash
# -> root@nginx-pod:/#
# curl localhost:80
# -> <!DOCTYPE html> nginx default html page ~

# 2. Local과 포트포워딩
# sudo kubectl port-forward pod/nginx-pod 80:80
# -> <!DOCTYPE html> nginx default html page ~


## pod 삭제
# kubectl delete pod nginx-pod